// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EasyPOS.CodeGen
{
    internal sealed partial class Vsix
    {
        public const string Id = "EasyPOS.CodeGen.34ec1012-0a92-46fa-a3bd-5bd268e0483c";
        public const string Name = "EasyPOS.CodeGen";
        public const string Description = @"Code Generation for Clean Architecture Project in .NET ";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Salman Farsy";
        public const string Tags = "EasyPOS.CodeGen";
    }
}
