// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EOS.CodeGen
{
    internal sealed partial class Vsix
    {
        public const string Id = "EOS.CodeGen.34ec1012-0a92-46fa-a3bd-5bd268e0483c";
        public const string Name = "EOS.CodeGen";
        public const string Description = @"EOS.CodeGen for generationg CQRS and Angular code againist an entity";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Salman Farsy";
        public const string Tags = "EOS.CodeGen";
    }
}
